### ISSUE TITLE
Using `: class` on protocols is deprecated

### ISSUE THREAD

**Issue by alejandroivan** [tadija/AELog#3]
https://github.com/tadija/AELog/blob/f559b3014d234c3997dc6272d9b29d705b6933c3/Sources/AELog/Log.swift#L57

This particular line is giving a warning while compiling on Xcode 13.2.1, as using `protocol SomeProtocol: class {}` is now deprecated.

Changing it to `protocol SomeProtocol: AnyObject {}` is the suggested way of updating it, according to Xcode. The warning message says:

`Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead`

**Comment by tadija** [comment]
Hi @alejandroivan, thanks for reporting, this is now fixed in the latest release (0.6.3).
