### ISSUE TITLE
crash when use Xcode13.3

### ISSUE THREAD

**Issue by Dast1Woop** [tadija/AELog#4]
Hi, when use Xcode13.3, it crash at:
let array = items.first.unsafelyUnwrapped as! [Any]
the message is:
Could not cast value of type 'Swift.String' (0x12f6398d8) to 'Swift.Array<Any>' (0x12f66fe88).

Help please,Thanks.

**Comment by Dast1Woop** [comment]
the code excute is: aelog("3")

**Comment by paulgee31** [comment]
I'm seeing the same issue.

Could not cast value of type 'Swift.String' (0x7fff8a86ca48) to 'Swift.Array<Any>' (0x7fff8a872e28).

**Comment by Dast1Woop** [comment]
> unsafelyUnwrapped

it seems that return type of 'unsafelyUnwrapped' method changed:
eg:
elog("3")
          xcode13.3 ,unsafelyUnwrapped, return String;
while xcode13.1,  unsafelyUnwrapped, return [Any]

**Comment by tadija** [comment]
Hi @Dast1Woop and @paulgee31, thanks for reporting, this is now fixed in the latest release (0.6.3).

**Comment by Dast1Woop** [comment]
> Hi @Dast1Woop and @paulgee31, thanks for reporting, this is now fixed in the latest release (0.6.3).

Got it.Thanks!
